### PR TITLE
storage/gcp: create a bucket on every test run

### LINKED ISSUE #1151: Flake in GCP tests
**Describe the bug**

Check out line 224-245 in this build: https://cloud.drone.io/gomods/athens/138/1/5

I've seen this across a few different PRs. Without looking in depth at the GCP code, I wonder if we're hitting a race condition?

**Error Message**

```
 expected: []string{"v1.1.0", "v1.2.0", "v1.3.0"} 
 actual : []string{"v1.3.0"} 
```

**To Reproduce**

It's tough to reproduce this because it's a flakey test. I suspect that it's due to a race condition.

**Expected behavior**

The tests should always pass if the code is correct

**Environment (please complete the following information):**
 - OS: Mac OS X 64 bit
 - Go version : 1.12
 - Buffalo Version : N/A
 - Proxy version : canary built from c59aa69848b3909f31f3a4ec796e167bf56075b3
 - Storage (fs/mongodb/s3 etc.) : GCP

**Additional context**

### PR DESCRIPTION
**Pull request by marwan-at-work**
Creates GCS buckets on the fly, deletes the bucket after tests finish 

Fixes #1151

### CODE REVIEW

File: pkg/storage/gcp/gcp_test.go [hunk 1]
```diff
@@ -2,14 +2,27 @@ package gcp
...
 )
 
+var bucketName = randomBucketName(os.Getenv("DRONE_PULL_REQUEST"))
+var strg *Storage
+
+func TestMain(m *testing.M) {
+	exitCode := m.Run()
+	if strg != nil {
+		strg.bucket.Delete(context.Background())
+	}
```
Comment (arschles) [inline pkg/storage/gcp/gcp_test.go]: @marwan-at-work would you be able to create and delete a bucket inside of each the individual test and benchmark? I think that would be a little easier to follow than the globals.

Comment (marwan-at-work) [reply pkg/storage/gcp/gcp_test.go]: @arschles that would require a refactoring of all the tests, we can do that as a follow up in my opinion if we deem it necessary. It would also be more costly because you'd be creating/destroying buckets 6x more per PR ;)

Comment (arschles) [reply pkg/storage/gcp/gcp_test.go]: Oh, I didn't see all 6 places. Where are the others beside `TestBackend` and `BenchmarkBackend`?

Comment (marwan-at-work) [reply pkg/storage/gcp/gcp_test.go]: @arschles to create/remove bucket for every single test suite, you'd have to have a new "setup" function before every test suite in this file: https://github.com/gomods/athens/blob/master/pkg/storage/compliance/tests.go

Which means every single storage we have tests for should update its signatures. 

It's a totally good solution and would allow our tests to be more flexible but it's a big lift for just fixing the ci/cd part :)

Comment (arschles) [reply pkg/storage/gcp/gcp_test.go]: @marwan-at-work I think I'm missing something because you already call `getStorage` at the beginning of `TestBackend` and `BenchmarkBackend` in the GCP tests. It seems like the only difference is that you need the global `strg` variable so that `TestMain` works properly, but `TestMain` doesn't need to exist in these GCP tests, does it?

Comment (marwan-at-work) [reply pkg/storage/gcp/gcp_test.go]: @arschles you're so right! I forgot that we actually call `compliance.RunTests` from with the test function itself, so we can actually defer cleaning up. 

Thanks for the call out :) I updated the code

Comment (marwan-at-work) [reply pkg/storage/gcp/gcp_test.go]: feel free to comment more, cuz i mighta missed a couple things here and there

**Comment by arschles** [comment]
@marwan-at-work this looks great! :shipit: 💥 🚀 

We have https://github.com/gomods/athens/issues/1165 to follow-up on the leaked google credentials thing. I'm gonna merge this now
