### PR TITLE
fix:  '/catalog' endpoint, which didn't allow fetch URL query parameters

### LINKED ISSUE #1236: token is not passed in /catalog from URL
**Describe the bug**
token/pagesize is not passed to /catalog from URL.

**Error Message**
token == "" instead of passed in value

image

image

**To Reproduce**
just pass any variable

**Expected behavior**
variables extracted from mux.Vars(r) is what's passed in URL

**Environment (please complete the following information):**
 - OS: [e.g. Linux 64bit]
 - Go version :1.12.4
 - Proxy version :master
 - Storage (fs/mongodb/s3 etc.) :

**Additional context**
https://stackoverflow.com/questions/31371111/mux-vars-not-working
Looks like shouldn't use `mux.Vars`

### PR DESCRIPTION
**Pull request by 5onic**
**What is the problem I am trying to address?**
Fixed `/catalog` endpoint which didn't retrieve correctly `token `and `pagesize` parameters.

**How is the fix applied?**

In order to correctly fetch `pagesize` and `token` parameters, I had replaced to `r.Query()` values instead of `mux.Vars()`.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1236

### CODE REVIEW

File: cmd/proxy/actions/catalog.go [hunk 1]
```diff
@@ -28,10 +27,12 @@ func catalogHandler(s storage.Backend) http.HandlerFunc {
 			w.WriteHeader(errors.KindNotImplemented)
 			return
 		}
+
 		lggr := log.EntryFromContext(r.Context())
-		vars := mux.Vars(r)
-		token := vars["token"]
-		pageSize, err := getLimitFromParam(vars["pagesize"])
+		urlQuery := r.URL.Query()
+		token := urlQuery.Get("token")
```
Comment (marwan-at-work) [inline cmd/proxy/actions/catalog.go]: you can remove the line above and just use `r.FormValue("token")` directly.

File: cmd/proxy/actions/catalog.go [hunk 2]
```diff
@@ -28,10 +27,12 @@ func catalogHandler(s storage.Backend) http.HandlerFunc {
...
+
+		pageSize, err := getLimitFromParam(urlQuery.Get("pagesize"))
```
Comment (marwan-at-work) [inline cmd/proxy/actions/catalog.go]: same here: `r.FormValue("pagesize")`

**Comment by 5onic** [comment]
@marwan-at-work No problems, fixed.

Thanks 👍
