### PR TITLE
Fixed Minio NewStorage to return the correct error

### LINKED ISSUE #1295: Minio MakeBucket errors not being returned.
**Describe the bug**
[See code for minio MakeBucket](https://github.com/gomods/athens/blob/a5eba1812bc48a4df1d9e7868288ed8feb31cdfd/pkg/storage/minio/minio.go#L39-L47)
If MakeBucket fails, the BucketExists call will overwrite the real error.  The result is a generic error being logged.

**Error Message**

```console
error getting storage configuration (Internal Server Error)
```
**To Reproduce**
Set the minio bucket name to an invalid name like "bucket_test".  The underscore is not an acceptable character.

```console
$ make dev
$ ATHENS_STORAGE_TYPE=minio ATHENS_MINIO_BUCKET_NAME=bucket_test make run
```

**Expected behavior**
Return the "MakeBucket" error.  For this specific error, the message should be:

```console
error getting storage configuration (Bucket name contains invalid characters)
```

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : go version go1.12.6 linux/amd64
 - Proxy version : N/A for this test case
 - Storage (fs/mongodb/s3 etc.) : Minio

I'll submit a pull request to address the issue in the next few days.  Will be away till Friday.

### PR DESCRIPTION
**Pull request by jamesnaftel**
**What is the problem I am trying to address?**
The incorrect error was being bubbled up when using an "_" in the in Minio bucket name.  It was returning the BucketExists error which uses a less strict form of error checking.

**How is the fix applied?**
The fix simply ignores the BucketExists error (the execution path is already inside an error condition) when there is an error.  If the bucket does exist, it correctly returns a storage backend.   I added test cases locally to minio_test.go since they are specific to minio and not the overall compliance tests.  Let me know if this isn't ok but I felt it made more sense.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1295

### CODE REVIEW

File: pkg/storage/minio/minio.go [hunk 1]
```diff
@@ -39,8 +39,9 @@ func NewStorage(conf *config.MinioConfig, timeout time.Duration) (storage.Backen
 	err = minioClient.MakeBucket(bucketName, region)
 	if err != nil {
 		// Check to see if we already own this bucket
-		exists, err := minioClient.BucketExists(bucketName)
-		if err == nil && !exists {
+		exists, _ := minioClient.BucketExists(bucketName)
+		if !exists {
```
Comment (arschles) [inline pkg/storage/minio/minio.go]: @jamesnaftel should we check `err` after this check, in case there was something else? Or will an error always be `nil` if `exists` is true?

Comment (jamesnaftel) [reply pkg/storage/minio/minio.go]: In the current minio-go client, true only gets return with a nil.  We could chain the BuckExists error in the failure case with the MakeBucket error but it looks like we would usually get the same error.

[minio-go: BucketExists](https://github.com/minio/minio-go/blob/26dec1a6ef2e943908b058233dbd091b411696d5/api-stat.go#L31)

Comment (arschles) [reply pkg/storage/minio/minio.go]: Got it, that makes sense. Thanks for explaining @jamesnaftel !
