### PR TITLE
storage/fs,minio: fix list module with same prefix

### LINKED ISSUE #1311: There is a bug in the minior/lister.go that can cause get wrong versions.
if moudule = "github.com/labstack/echo",objectCh will contains the version of module "github.com/labstack/echo/v4" ,  because list all the file related to searchPrefix.

image

### PR DESCRIPTION
**Pull request by yittg**
check semver and go.mod existence to verify a module version

Fixes #1311

### CODE REVIEW

**Comment by yittg** [comment]
cc @marwan-at-work @marpio

File: pkg/storage/compliance/tests.go [hunk 1]
```diff
@@ -63,40 +63,37 @@ func testNotFound(t *testing.T, b storage.Backend) {
...
-			version,
-			mock.Mod,
-			mock.Zip,
-			mock.Info,
-		)
-		require.NoError(t, err, "Save for storage failed")
+	modVers := map[string][]string{
+		"github.com/one/two":       {"v1.1.0", "v1.2.0", "v1.3.0"},
+		"github.com/one/two/v2":    {"v2.1.0"},
+		"github.com/one/two/three": {"v0.9.0"},
```
Comment (marwan-at-work) [inline pkg/storage/compliance/tests.go]: let's keep the old test of `github.com/one/two-other != github.com/one/two` to this new mix of scenarios.

File: pkg/storage/fs/lister.go [hunk 2]
```diff
@@ -3,12 +3,35 @@ package fs
...
 
+func (l *storageImpl) isSemVerDir(module string, verFileInfo os.FileInfo) (bool, error) {
+	if !verFileInfo.IsDir() {
+		return false, nil
+	}
+	ver := verFileInfo.Name()
+	if ver[0] != 'v' {
+		return false, nil
+	}
+	if _, err := semver.NewVersion(ver[1:]); err != nil {
```
Comment (marwan-at-work) [inline pkg/storage/fs/lister.go]: Go's interpretation of SemVer is not the same as the Spec which is what core-os I believe follows. Therefore, this could lead to some false negatives. You can check out godoc.org/golang.org/x/mod/semver for Go's interpretation.

File: pkg/storage/minio/lister.go [hunk 3]
```diff
@@ -23,21 +36,15 @@ func (l *storageImpl) List(ctx context.Context, module string) ([]string, error)
...
+	ret := []string{}
 	for _, object := range objectCh.Contents {
 		if object.Err != nil {
 			return nil, errors.E(op, object.Err, errors.M(module))
 		}
-		parts := strings.Split(object.Key, "/")
-		ver := parts[len(parts)-2]
-		if _, ok := dict[ver]; !ok {
-			dict[ver] = struct{}{}
+		if ver, ok := l.getModuleSemVerFromKey(module, object.Key); ok {
```
Comment (marwan-at-work) [inline pkg/storage/minio/lister.go]: same as above, no need for this function. You can check that the path is correct by just making sure the module paths are equal. Therefore, let's keep the old code and add those 3 new lines: 

```
modpath := strings.Join(parts[:len(parts)-2], "/")
if modpath != module {
	continue
}
```

Comment (yittg) [reply pkg/storage/minio/lister.go]: basically agree, a bit different from the 3 new lines with checking go mod key only

File: pkg/storage/fs/lister.go [hunk 4]
```diff
@@ -24,7 +44,9 @@ func (l *storageImpl) List(ctx context.Context, module string) ([]string, error)
 	}
 	ret := []string{}
 	for _, fileInfo := range fileInfos {
-		if fileInfo.IsDir() {
+		if ok, err := l.isSemVerDir(module, fileInfo); err != nil {
```
Comment (marwan-at-work) [inline pkg/storage/fs/lister.go]: let's short-circuit this by removing the `isSemVerDir` and just doing this check: `fileInfo.IsDir() && len(fileInfo.Name()) > 2`

Comment (marwan-at-work) [reply pkg/storage/fs/lister.go]: @marpio pointed out that checking length > 2 wouldn't work because you might have `v10` which is len == 3 and so on and so forth. 

Basically, I'm hoping to get around making extra system calls because the /list endpoint is already a slow operation. 

Two ways to get around this is by 
1. Just checking if `!strings.Contains(version, ".")` 
2. By checking that the directory name is *not* `vN` where N is a valid integer

Comment (yittg) [reply pkg/storage/fs/lister.go]: @marwan-at-work @marpio thanks for suggestions about performance.

Only check `vN` is not enough, say we have a module `github.com/one/two` with some versions cached, a query for module `github.com/one` is valid which is expected to get nothing.

I committed another fix to only check semver without stats `go.mod` file, the only edge case left  uncovered i think is that a module contains a full semver part like `github.com/one/v1.1.1`, which maybe no need to deal with.

**Comment by yittg** [comment]
@arschles @marwan-at-work  @marpio PTAL again.

File: pkg/storage/fs/lister.go (hunk 4 above)
Comment (marwan-at-work) [reply pkg/storage/fs/lister.go]: @yittg then let's go with the first option, I think it should be enough because no major version will ever have a `.` in it. 
In other words, there shouldn't be a need to use `semver` package at all, right?

Comment (yittg) [reply pkg/storage/fs/lister.go]: I don't think so, dot in import path is valid besides in host part, maybe rarely though, not only in version. Full semver check is essential, i think.

Comment (marwan-at-work) [reply pkg/storage/fs/lister.go]: @yittg right, but when you're inside a module folder (in fs storage), there are no sub packages, there are only versions (v0.3.0/...) and major versions such as (v2/v2.1.3/...).

Comment (marwan-at-work) [reply pkg/storage/fs/lister.go]: would sub modules be included there by any chance?

Comment (marwan-at-work) [reply pkg/storage/fs/lister.go]: It might be worth making an example in github.com/athens-artifacts

Comment (yittg) [reply pkg/storage/fs/lister.go]: Say we have a repo `github.com/athens-artifacts/a.b.c`, athens will save a cache in fs by `go get github.com/athens-artifacts/a.b.c`, next `go get github.com/athens-artifacts` is a valid request may not correct will got a list contains `a.b.c` which is not a version though.

Comment (marwan-at-work) [reply pkg/storage/fs/lister.go]: @yittg that makes sense, I actually created https://github.com/athens-artifacts/submod-conflict where we can add real tests to (in another PR) 

You can notice that `v1.9.9` is actually not accepted as a sub-module. So option 2 actually does work (parsing vN). But sub-modules will also be included. So checking that semver.Canonical should account for both cases. 

Thanks again for looking into this :+1:

Comment (yittg) [reply pkg/storage/fs/lister.go]: yeah, some particular integrated tests for these senarios are required.
