### PR TITLE
Set GO111MODULE to auto in golint script– #1743

### LINKED ISSUE #1743: `golint` checks in `make verify` throw GOROOT error
**Describe the bug**

Linting during `verify` Makefile task returns error for each module in Athens as "not in GOROOT" with the `GO111MODULE=off` setting.

**Error Message**

<pre>
```package _/Users/me/path/to/athens/cmd/proxy is not in GOROOT (/usr/local/Cellar/go/1.17.3/libexec/src/_/Users/me/path/to/go/athens/cmd/proxy)
```
</pre>

**To Reproduce**

`make verify`

**Expected behavior**

No errors thrown by `golint` and status 0 returned

**Environment (please complete the following information):**

 - OS: Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64 (macOS Big Sur 11.6.1)
 - Go version : 1.17.3
 - Proxy version : N/A
 - Storage (fs/mongodb/s3 etc.) : N/A

**Additional context**

The current verify script also returns status 0 but clogs up output with lines that look like errors. I am possibly not familiar enough with the workings of `GO111MODULE` but setting this to `on` seems to completely clear up the issue, and I don't understand why we would run listing with the modules option deliberately off.

### PR DESCRIPTION
**Pull request by rbrtl**
As mentioned in #1743 the Go modules environment flag is set to `off`
in the script which appears to cause a warning message for each module
of the codebase that it is "not in GOROOT".

Set to `auto` as this allows the same build to be run the original way
should someone choose to delete the `go.mod` file from the project root.

## What is the problem I am trying to address?

Golint warning for each submodule of Athens "package not in GOROOT" when running Make target `verify`

## How is the fix applied?

Set `GO111MODULE=auto` in `./scripts/check_golint.sh` 

## What GitHub issue(s) does this PR fix or close?

Fixes #1743

### CODE REVIEW

File: scripts/check_golint.sh [hunk 1]
```diff
@@ -4,4 +4,4 @@
 # Run the linter on everything except generated code
 set -euo pipefail
 
-golint -set_exit_status $(GO111MODULE=off go list ./... | grep -v '/mocks')
+golint -set_exit_status $(GO111MODULE=auto go list ./... | grep -v '/mocks')
```
Comment (manugupt1) [inline scripts/check_golint.sh:7]: Thanks for this change. I believe we have now started to build for go1.17.

Go1.17 will ignore this flag: https://go.dev/blog/go116-module-changes.
I believe: https://github.com/gomods/athens/pull/815 was an explicit choice though to make the CI faster

I am not sure if this will work anymore. Maybe we should just remove it: cc @marwan-at-work ?

Comment (marwan-at-work) [reply scripts/check_golint.sh:7]: Yes I think it's worth removing. Also, do we even have `/mock`? I wonder if we can do `golinst ./...` or `golint go list ./...`

Comment (rbrtl) [reply scripts/check_golint.sh:7]: I'll do it right and raise another PR!

Comment (rbrtl) [reply scripts/check_golint.sh]: I checked `golint ./...` vs. `golint $(go list ./...)`... I am struggling to prove it definitively prove that the former is linting all the files covered by the latter. The `go list` subshell command version takes noticeably longer, but that's not to say, necessarily, that the `golint` command isn't examining all the correct files. Any input on that much appreciated.

Comment (manugupt1) [reply scripts/check_golint.sh]: Thank you for doing it right. I just noticed that even golint is deprecated. 
https://github.com/golang/lint
Would you be able to update the code to use `staticcheck` and `go vet`

We already use govet
https://github.com/gomods/athens/blob/fd54babfae1d5fea4f089789e27b23956532f84c/.drone.yml#L32

I would probably just start with govet, open an issue and then do a separate PR for staticcheck. I hope this helps.

**Comment by manugupt1** [comment]
Thanks for making this change. Also congrats on your first PR 🎉

**Review by manugupt1 — APPROVED** [review]

**Comment by arschles** [comment]
@rbrtl this is awesome - thank you!
