### PR TITLE
Use glob matching for package paths (Fix #1408)

### LINKED ISSUE #1408: Download directive paths do not match subpackages like GOPRIVATE
**Describe the bug**
When using a 'Download File' to configure download modes, it is not possible to match all packages with an import path at a domain level. For example, private repos behind a firewall.

**To Reproduce**
1. Create a `download.hcl` file and configure Athens to use it via `DownloadMode` config.

```hcl
downloadURL = "https://proxy.golang.org"

mode = "async_redirect"

download "*.example.com/*" {
    mode = "sync"
}
```

**Expected behavior**
All modules from _anything_ `example.com` should not redirect, but should download synchronously.

**Actual behavior**
All requests are redirected to proxy.golang.org (which is exactly what I **don't** want).

**Environment (please complete the following information):**
 - OS: All
 - Go version: 1.13
 - Proxy version: master
 - Storage: All

**Additional context**
The problem appears to stem from using `path.Match` for glob matching. For `path.Match`, `*` matches any sequence of **non-/** characters.

In order to support this as is, I need to define an indeterminate number of possible directory matches. For example:

```hcl
download "*.example.com/*" {
    mode = "sync"
}

download "*.example.com/*/*" {
    mode = "sync"
}

download "*.example.com/*/*/*" {
    mode = "sync"
}

download "*.example.com/*/*/*/*" {
    mode = "sync"
}

download "*.example.com/*/*/*/*/*" {
    mode = "sync"
}
```

The `GOPRIVATE`, `GONOPROXY`, and `GONOSUMDB` environment variable seem to handle this somehow.  I can define `GOPRIVATE="*.example.com"` and it works as expected for all packages that start with any `example.com` domain.

### PR DESCRIPTION
**Pull request by jorng**
This will match the behavior of GOPRIVATE/GONOPROXY/GONOSUMDB

**What is the problem I am trying to address?**
This addresses an issue with download directives where subpackages do not match if there are any additional `/` characters (counter to how GOPRIVATE/GONOPROXY/GONOSUMDB all work)

**How is the fix applied?**
Matched the behavior used by `go mod`. Shared the new matching code with SumDB matcher as well.

**Mention the issue number it fixes or add the details of the changes if it doesn't have a specific issue.**

Fixes #1408

### CODE REVIEW

File: pkg/paths/path.go [hunk 1]
```diff
@@ -50,3 +52,28 @@ func GetAllParams(r *http.Request) (*AllPathParams, error) {
...
+func MatchGlobPattern(pattern, name string) (bool, error) {
+	const op errors.Op = "paths.MatchGlobPattern"
+	pCount := strings.Count(pattern, "/")
+	nCount := strings.Count(name, "/")
+
+	for nCount > pCount {
+		i := strings.LastIndex(name, "/")
+		if i == -1 {
+			break
+		}
```
Comment (marwan-at-work) [inline pkg/paths/path.go]: Is this block ever possible to be true?

File: pkg/paths/path.go [hunk 2]
```diff
@@ -50,3 +52,28 @@ func GetAllParams(r *http.Request) (*AllPathParams, error) {
...
+		name = name[:i]
+		nCount = strings.Count(name, "/")
```
Comment (marwan-at-work) [inline pkg/paths/path.go]: why not keep the same implementation as `matchesPattern` above? That one (copied from the Go source code) has one call to strings.Count while this implementation has N+2 calls?

File: pkg/download/mode/mode.go [hunk 3]
```diff
@@ -130,7 +130,7 @@ func (d *DownloadFile) Match(mod string) Mode {
 // the top level downloadURL is returned.
 func (d *DownloadFile) URL(mod string) string {
 	for _, p := range d.Paths {
-		if hasMatch, err := path.Match(p.Pattern, mod); hasMatch && err == nil {
+		if hasMatch, err := paths.MatchGlobPattern(p.Pattern, mod); hasMatch && err == nil {
```
Comment (marwan-at-work) [inline pkg/download/mode/mode.go]: We're only checking `if err == nil`. In other words, we're really not doing anything if `err != nil` so we might as well be explicit about ignoring it so we should just put `_` and check for `hasMatch`

File: pkg/paths/path.go (hunk 2 above)
Comment (jorng) [reply pkg/paths/path.go]: Good question. I actually wrote this several weeks ago; before the `matchesPattern` implementation (I just received permission for the postback).  It was written to be understandable, and not too much copy-paste from the Go source code.

After rebasing and seeing the new `matchesPattern` function, I benchmarked it. `MatchGlobPattern` runs ~4-7% faster than `matchesPattern`, so I left it with my new implementation.

```
name                        old time/op    new time/op    delta
PathMatch/MatchPattern/1-8     131ns ± 0%     125ns ± 0%  -4.58%
PathMatch/MatchPattern/2-8     148ns ± 0%     138ns ± 0%  -6.76%
PathMatch/MatchPattern/3-8     168ns ± 0%     160ns ± 0%  -4.76%
PathMatch/MatchPattern/4-8     200ns ± 0%     193ns ± 0%  -3.50%
PathMatch/MatchPattern/5-8     215ns ± 0%     207ns ± 0%  -3.72%
PathMatch/MatchPattern/6-8     236ns ± 0%     227ns ± 0%  -3.81%
PathMatch/MatchPattern/7-8     270ns ± 0%     249ns ± 0%  -7.78%
PathMatch/MatchPattern/8-8     290ns ± 0%     272ns ± 0%  -6.21%
PathMatch/MatchPattern/9-8     313ns ± 0%     292ns ± 0%  -6.71%
```

> The `/`+digit for each benchmark is the number of `/` in the pattern.

File: pkg/paths/path.go (hunk 1 above)
Comment (jorng) [reply pkg/paths/path.go]: As it stands, it shouldn't. I can remove it if needed. It's there as a backup, in case the code ever changes.

File: pkg/download/mode/mode.go (hunk 3 above)
Comment (jorng) [reply pkg/download/mode/mode.go]: Agreed, I only wrote it this way to be a drop-in replacement, the `err == nil` was already there.

Comment (jorng) [reply pkg/download/mode/mode.go]: Fixed in d81c837

File: pkg/paths/path.go (hunk 2 above)
Comment (marwan-at-work) [reply pkg/paths/path.go]: Thanks for the stats. It definitely seems weird that more strings.Count calls is more performant.

I ran some benchmarks against the two functions with the following input

`MatchGlobPattern("github.com/one/two/*", "github.com/one/two/three/four/five/six/seven")`

and 

`matchesPattern("github.com/one/two/*", "github.com/one/two/three/four/five/six/seven")`

And the first one yielded `167 ns/op` while the second one yielded `115 ns/op` which makes a little more sense. 

I'm a bit curious as to how you got your stats, do you mind putting them in a gist? Just so I can see what the results are on my machine. 

Interestingly enough, `benchstat` returned this: 

```
name   old time/op    new time/op    delta
Match-8     167ns ± 0%     115ns ± 0%   ~     (p=1.000 n=1+1)
```

Where the `~` indicates that the difference is not significant enough :) 

That said, I think it's safe to keep the Go implementation because they have far more robust tests on their implementations and it's good to keep the code consistent.

Comment (jorng) [reply pkg/paths/path.go]: Ahh, looks like I made a mistake on my benchmark. The number of slashes between the pattern and the target were always matching. 

I can switch out my function for `matchesPattern`.

Comment (jorng) [reply pkg/paths/path.go]: So my original benchmark was testing increasing lengths of `pattern`, but it's much more likely that `pattern` will be short, and `target` long. So the `matchesPattern` implementation is much better, as it runs in constant time, even with increasing `target` length.

I've added a Benchmark so this can be monitored / compared in the future if needed.

**Comment by jorng** [comment]
Should all be resolved now. Let me know if there's anything else @marwan-at-work.
