### PR TITLE
Set correct content type and send once

### LINKED ISSUE #1930: Duplicate HTTP `Content-Type` header
**Describe the bug**
It seems Athen's HTTP server delivers duplicate HTTP `Content-Type` headers. It's not breaking anything as far as I can tell but my reverse proxy log is full of warnings regarding it.

```console
$ curl -v http://athens/sumdb/sum.golang.org/lookup/modernc.org/token@v1.0.1 |& grep -i content-Type:
< Content-Type: application/json
< Content-Type: text/plain; charset=UTF-8
$ curl -v http://sum.golang.org/lookup/modernc.org/token@v1.0.1 |& grep -i content-Type:
< Content-Type: text/plain; charset=UTF-8
```

**To Reproduce**
Run above curl against athens

**Expected behavior**
A single `Content-Type` header.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 in a Docker container running `gomods/athens`
 - Go version : `go1.20.12 linux/amd64`
 - Proxy version : `v0.13.1`
 - Storage (fs/mongodb/s3 etc.) : `fs`
 
**Additional context**
Potentialyl relevant config option:`ATHENS_GO_BINARY_ENV_VARS=GOPROXY=proxy.golang.org,direct`
Header seems to be coming from here: https://github.com/gomods/athens/blob/b72f01b7bcfc12b983474be417285f415f590d3a/pkg/middleware/content_type.go#L11

### LINKED ISSUE #1958: Introduction pages are broken
**Describe the bug**

The bug is two fold:

1. Introduction pages do not appear to load the file from disk the way the configuration claims. There's tests that assert this behavior and I've simulated it locally, but when I ran it in production it doesn't seem to work.
2. The `Content-Type` header that Chrome receives first is the one that is honored. In our case, the right content type is sent, but it's second because of an [existing bug in Athens](https://github.com/gomods/athens/issues/1930). Firefox doesn't seem to do this, it takes the last Content-Type header.

**Error Message**
The content is rendered as `application/json` and the in-memory template is loaded even when a file is specified.

**To Reproduce**

1. Specify a location with https://github.com/gomods/athens/blob/main/config.dev.toml#L174

1. Launch an image

1. `curl -v` the root endpoint

**Expected behavior**

An HTML page is shown, if specified the custom one, and it is rendered as HTMl by the browser.

**Environment (please complete the following information):**
 - OS: Linux 64bit
 - Go version : 1.22
 - Proxy version : v0.14.0
 - Storage (fs/mongodb/s3 etc.) : FS

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by matt0x6F**
## What is the problem I am trying to address?

Content types are being sent more than once and are often incorrectly set. See #1930

## How is the fix applied?

Set the content type directly on handlers and remove content type middleware

## What GitHub issue(s) does this PR fix or close?

Fixes #1930
Fixes #1958

### CODE REVIEW

**Comment by matt0x6F** [comment]
You can test this locally by running athens from the repo. Then use curl:
```
❯ curl -v localhost:3000
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/html
< Date: Thu, 23 May 2024 02:11:51 GMT
< Transfer-Encoding: chunked
< 
<!DOCTYPE html>
<html>
<head>
        <title>Athens</title>
        <style>
                body {
                        font-family: Arial, sans-serif;
                        margin: 20px;
                }

                pre {
                                background-color: #f4f4f4;
                                padding: 5px;
                                border-radius: 5px;
                                width: fit-content;
                                padding: 10px;
                }


                code {
                        background-color: #f4f4f4;
                        padding: 5px;
                        border-radius: 5px;
                }

        </style>
</head>
<body>

        <h1>Welcome to Athens</h1>

        <h2>Configuring your client</h2>
        <pre>GOPROXY=http://localhost:3000,direct</pre>


        <h2>How to use the Athens API</h2>
        <p>Use the <a href="/catalog">catalog</a> endpoint to get a list of all modules in the proxy</p>

        <h3>List of versions</h3>
        <p>This endpoint returns a list of versions that Athens knows about for <code>acidburn/htp</code>:</p>
        <pre>GET http://localhost:3000/github.com/acidburn/htp/@v/list</pre>

        <h3>Version info</h3>
        <p>This endpoint returns information about a specific version of a module:</p>
        <pre>GET http://localhost:3000/github.com/acidburn/htp/@v/v1.0.0.info</pre>
        <p>This returns JSON with information about v1.0.0. It looks like this:
        <pre>{
        "Name": "v1.0.0",
        "Short": "v1.0.0",
        "Version": "v1.0.0",
        "Time": "1972-07-18T12:34:56Z"
}</pre>

        <h3>go.mod file</h3>
        <p>This endpoint returns the go.mod file for a specific version of a module:</p>
        <pre>GET http://localhost:3000/github.com/acidburn/htp/@v/v1.0.0.mod</pre>
        <p>This returns the go.mod file for version v1.0.0. If http://localhost:3000/github.com/acidburn/htp version v1.0.0 has no dependencies, the response body would look like this:</p>
        <pre>module github.com/acidburn/htp</pre>

        <h3>Module sources</h3>
        <pre>GET http://localhost:3000/github.com/acidburn/htp/@v/v1.0.0.zip</pre>
        <p>This is what it sounds like — it sends back a zip file with the source code for the module in version v1.0.0.</p>

        <h3>Latest</h3>
        <pre>GET http://localhost:3000/github.com/acidburn/htp/@latest</pre>
        <p>This endpoint returns the latest version of the module. If the version does not exist it should retrieve the hash of latest commit.</p>

</body>
</html>
* Connection #0 to host localhost left intact
```

File: cmd/proxy/actions/app.go [hunk 1]
```diff
@@ -52,7 +52,6 @@ func App(logger *log.Logger, conf *config.Config) (http.Handler, error) {
 			SSLRedirect:     conf.ForceSSL,
 			SSLProxyHeaders: map[string]string{"X-Forwarded-Proto": "https"},
 		}).Handler,
-		mw.ContentType,
```
Comment (nrwiersma) [inline cmd/proxy/actions/app.go:55]: Instead of removing this, perhaps adding a check, that is no `Content-Type` is set, then adding one. This would ensure there is always something present?

Comment (matt0x6F) [reply cmd/proxy/actions/app.go:55]: I was going to do that, but I think all middle ware is executed before the route code.

To make matters more complicated, Set() doesn't seem to override the header, instead it's sent twice when set twice.

Comment (nrwiersma) [reply cmd/proxy/actions/app.go:55]: Yeah, reasonable point. Then this middleware should be removed.

Comment (matt0x6F) [reply cmd/proxy/actions/app.go:55]: I'm going to give this a second test run tonight, just to double check what I've told you here, but I'm 99% positive.

Comment (matt0x6F) [reply cmd/proxy/actions/app.go:55]: I validated that what I stated is the case. The `Set()` method does not seem to override existing headers by the same name:

With `mw.ContentType`:
```
❯ curl -v http://localhost:3000/sumdb/sum.golang.org/lookup/github.com/matt0x6f/athens-test-repo@v1.0.0
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /sumdb/sum.golang.org/lookup/github.com/matt0x6f/athens-test-repo@v1.0.0 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Allow-Origin: *
< Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< Cache-Control: public, max-age=10800
< Content-Length: 389
< Content-Security-Policy-Report-Only: script-src 'none'; report-uri https://csp.withgoogle.com/csp/goa-fa2dfb7c
< Content-Type: application/json
< Content-Type: text/plain; charset=UTF-8
< Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="goa-fa2dfb7c"
< Date: Sun, 02 Jun 2024 19:15:50 GMT
< Expires: Sun, 02 Jun 2024 22:15:50 GMT
< Report-To: {"group":"goa-fa2dfb7c","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/goa-fa2dfb7c"}]}
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 0
< 
25262111
github.com/matt0x6f/athens-test-repo v1.0.0 h1:QyR4h2t/LX1F5R9ipGD0Xy40Ti7wXWQtmZGb/ULfX4U=
github.com/matt0x6f/athens-test-repo v1.0.0/go.mod h1:AK0IEu9FDueopVcCOW9cuKpAZUymWO769GslenSoEzQ=

go.sum database tree
26548605
8GJ63plZadguUEd9PQ6EJwYIfgeb/nbtNfPhRA92Ux4=

— sum.golang.org Az3grsyr0VoqcgV66Tvivr6bW8C9xN6nIp6Rxx+jAoVEgtifXoJZElj+8OyZ7UUPMCTe0RKO0qSFK3Huc37fic2Rogk=
* Connection #0 to host localhost left intact
```

without:
```
❯ curl -v http://localhost:3000/sumdb/sum.golang.org/lookup/github.com/matt0x6f/athens-test-repo@v1.0.0
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /sumdb/sum.golang.org/lookup/github.com/matt0x6f/athens-test-repo@v1.0.0 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Allow-Origin: *
< Age: 194
< Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< Cache-Control: public, max-age=10800
< Content-Length: 389
< Content-Security-Policy-Report-Only: script-src 'none'; report-uri https://csp.withgoogle.com/csp/goa-fa2dfb7c
< Content-Type: text/plain; charset=UTF-8
< Cross-Origin-Opener-Policy-Report-Only: same-origin; report-to="goa-fa2dfb7c"
< Date: Sun, 02 Jun 2024 19:15:50 GMT
< Expires: Sun, 02 Jun 2024 22:15:50 GMT
< Report-To: {"group":"goa-fa2dfb7c","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/goa-fa2dfb7c"}]}
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 0
< 
25262111
github.com/matt0x6f/athens-test-repo v1.0.0 h1:QyR4h2t/LX1F5R9ipGD0Xy40Ti7wXWQtmZGb/ULfX4U=
github.com/matt0x6f/athens-test-repo v1.0.0/go.mod h1:AK0IEu9FDueopVcCOW9cuKpAZUymWO769GslenSoEzQ=

go.sum database tree
26548605
8GJ63plZadguUEd9PQ6EJwYIfgeb/nbtNfPhRA92Ux4=

— sum.golang.org Az3grsyr0VoqcgV66Tvivr6bW8C9xN6nIp6Rxx+jAoVEgtifXoJZElj+8OyZ7UUPMCTe0RKO0qSFK3Huc37fic2Rogk=
* Connection #0 to host localhost left intact
```

We're looking for `text/plain` on this particular endpoint.

Comment (nrwiersma) [reply cmd/proxy/actions/app.go:55]: https://github.com/golang/go/blob/master/src/net/url/url.go#L932

There is something else going on I think.

**Review by nrwiersma — APPROVED** [review]

File: cmd/proxy/actions/app.go (hunk 1 above)
Comment (matt0x6F) [reply cmd/proxy/actions/app.go:55]: Yeah, I agree, something is weird. When I click through what our `mw.ContentType` is referencing it uses the `response.Header()` method, which points to [this](https://github.com/golang/go/blob/master/src/net/http/header.go#L39). Same documentation as the URL header, but a different set of code.

I'm not really sure why it doesn't work as described. Both the middleware and the handler are working on the same API.
